// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5k4khJT_04dUA7lfk2RF98p65j6hMKnA',
    appId: '1:633819536577:android:0f6d04998a8cf0a2a3c840',
    messagingSenderId: '633819536577',
    projectId: 'bisat-f9f04',
    storageBucket: 'bisat-f9f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_T8QC8UCZIH0pNE947U2B3fb1eLOH6nU',
    appId: '1:633819536577:ios:d2a0c5a14a465e30a3c840',
    messagingSenderId: '633819536577',
    projectId: 'bisat-f9f04',
    storageBucket: 'bisat-f9f04.appspot.com',
    androidClientId:
        '633819536577-42mi6m90i9md0n53qgaarujfrusf9agv.apps.googleusercontent.com',
    iosClientId:
        '633819536577-508bmu73p59gopkgt8opak49qs2bqq89.apps.googleusercontent.com',
    iosBundleId: 'com.arma.supermarket',
  );
}
